/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as FeatureThemesRouteImport } from './routes/feature-themes'
import { Route as FieldPlaygroundRouteImport } from './routes/field-playground'
import { Route as PalettesRouteImport } from './routes/palettes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureThemesRoute = FeatureThemesRouteImport.update({
  id: '/feature-themes',
  path: '/feature-themes',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldPlaygroundRoute = FieldPlaygroundRouteImport.update({
  id: '/field-playground',
  path: '/field-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PalettesRoute = PalettesRouteImport.update({
  id: '/palettes',
  path: '/palettes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/feature-themes': typeof FeatureThemesRoute
  '/field-playground': typeof FieldPlaygroundRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/feature-themes': typeof FeatureThemesRoute
  '/field-playground': typeof FieldPlaygroundRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/feature-themes': typeof FeatureThemesRoute
  '/field-playground': typeof FieldPlaygroundRoute
  '/palettes': typeof PalettesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/charts' | '/feature-themes' | '/field-playground' | '/palettes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/charts' | '/feature-themes' | '/field-playground' | '/palettes'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/feature-themes'
    | '/field-playground'
    | '/palettes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRoute
  FeatureThemesRoute: typeof FeatureThemesRoute
  FieldPlaygroundRoute: typeof FieldPlaygroundRoute
  PalettesRoute: typeof PalettesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-themes': {
      id: '/feature-themes'
      path: '/feature-themes'
      fullPath: '/feature-themes'
      preLoaderRoute: typeof FeatureThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-playground': {
      id: '/field-playground'
      path: '/field-playground'
      fullPath: '/field-playground'
      preLoaderRoute: typeof FieldPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palettes': {
      id: '/palettes'
      path: '/palettes'
      fullPath: '/palettes'
      preLoaderRoute: typeof PalettesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRoute,
  FeatureThemesRoute: FeatureThemesRoute,
  FieldPlaygroundRoute: FieldPlaygroundRoute,
  PalettesRoute: PalettesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
